#!/bin/bash
# $File: client-file
# $Date: Sat Mar 03 00:09:42 2012 +0800
# $Author: jiakai <jia.kai66@gmail.com>


. $(dirname $0)/config

if [ -z "$1" -o -z "$2" ]
then
	echo "Usage: $0 <server addr> <file path>"
	exit -1
fi

socat -u open:$2 tcp:$1:$PORT_FILE

