#!/bin/bash -e
# $File: tex2pdf
# $Date: Tue Apr 22 10:41:43 2014 +0800
# $Author: jiakai <jia.kai66@gmail.com>

src=$1

if [ -z "$src" ]
then
	echo "usage: $0 <xelatex source>"
	exit -1
fi

latexmk --8bit -xelatex -shell-escape $src
latexmk -c

evince ${src%.tex}.pdf

# vim: ft=sh
